Add retry flags to curl, to survive small artifact server hiccups

diff --git a/deploy-artifact b/deploy-artifact
--- a/deploy-artifact
+++ b/deploy-artifact
@@ -13,12 +13,33 @@ cleanup()
 	rm -rf "${TARGET_TMP_DIR}" &>/dev/null
 }
 
+curl_retry()
+{
+	curl \
+		--retry-connrefused \
+		--retry-delay 3 \
+		--retry 10 \
+		"${@}"
+}
+
+curl_get()
+{
+	curl_retry \
+		--location \
+		--silent \
+		--fail \
+		--disallow-username-in-url \
+		"${@}"
+}
+
 download()
 {
 	local URL="${1}"
 	local TGT="${2}"
 	# The artifact is there, so pull it into the destination
-	curl -L --fail -s -o "${TGT}" "${URL}" || fail "Failed to download the artifact from [${URL}] into [${TGT}]"
+	curl_get \
+		--output "${TGT}" \
+		"${URL}" || fail "Failed to download the artifact from [${URL}] into [${TGT}]"
 }
 
 usage()
@@ -95,7 +116,7 @@ HTTP_CODE="$(curl -L -s -o /dev/null -w "%{http_code}" "${CHECK_URL}")"
 # Same with the version and the checksum, but it's OK if these aren't there b/c
 # we can come up with defaults
 
-NEW_VER="$(curl -L -s --fail "${VERSION_URL}" 2>/dev/null || true)"
+NEW_VER="$(curl_get "${VERSION_URL}" 2>/dev/null || true)"
 grep -q '<!DOCTYPE html>' <<< "${NEW_VER}" && NEW_VER=""
 [ -n "${NEW_VER}" ] || NEW_VER="(unknown)"
 
@@ -103,7 +124,7 @@ grep -q '<!DOCTYPE html>' <<< "${NEW_VER}" && NEW_VER=""
 SUM=""
 
 # If we're not forcing a local hash computation, we try to download the cached value
-as_boolean "${FORCE_HASHES}" || SUM="$(curl -L -s --fail "${CHECKSUM_URL}" 2>/dev/null || true)"
+as_boolean "${FORCE_HASHES}" || SUM="$(curl_get "${CHECKSUM_URL}" 2>/dev/null || true)"
 
 # If the sum is invalid, or we're requesting local checksum computation, we do just that
 if [[ ! "${SUM}" =~ ^[0-9a-f]{64}$ ]] ; then
